### ISSUE TITLE
Investigate Segfault 

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#189]
// DELETE IRRELEVANT PARTS OF TEMPLATE FOR YOUR ISSUE 

**Describe the bug**
most all functionality of the cli results in segfaulting error. could just be that my machine needs a reboot, but needs investigation 

**To Reproduce**
1. ./build/kabanero login or logout results in segfault

**Screenshots**
```
claudias-mbp kabanero-command-line =>./build/kabanero logout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x14215ba]

goroutine 1 [running]:
github.com/kabanero-io/kabanero-command-line/cmd.sendHTTPRequest(0x1516350, 0x4, 0xc0000c2460, 0x49, 0x0, 0x0, 0x0, 0x1516ccb, 0x6, 0xc0000c2460)
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/cmd/sync.go:98 +0xe6a
github.com/kabanero-io/kabanero-command-line/cmd.glob..func6(0x18e7660, 0x190ce18, 0x0, 0x0, 0x0, 0x0)
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/cmd/logout.go:32 +0xed
github.com/kabanero-io/kabanero-command-line/vendor/github.com/spf13/cobra.(*Command).execute(0x18e7660, 0x190ce18, 0x0, 0x0, 0x18e7660, 0x190ce18)
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/kabanero-io/kabanero-command-line/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x18e6ce0, 0x18ac780, 0xc000000180, 0xc000101f50)
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/kabanero-io/kabanero-command-line/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/vendor/github.com/spf13/cobra/command.go:800
github.com/kabanero-io/kabanero-command-line/cmd.Execute(0x15b2ca0, 0x5)
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/cmd/root.go:170 +0x56
main.main()
	/Users/claudia.yanibm.com/go/src/github.com/kabanero-io/kabanero-command-line/main.go:26 +0x39
```

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by s1cyan** [comment]
i am a big bozo
CONNECT UR VPN
